# This workflow will do a clean install of node dependencies, build the source code and run tests and deploy to binary repo
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  push:
    branches: ["master", 'main', 'develop', 'uat']
    tags: ['*.*.*']

jobs:
  build:
    name: "build test and deploy"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      - name: Cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 #v5.1.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules
          # An explicit key for restoring and saving the cache
          key: foodpantry-labelbuster-node_modules-${{ hashFiles('package.json') }}
          restore-keys: |
            foodpantry-labelbuster-node_modules-${{ hashFiles('package.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test

      - name: Archive artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: dist
          path: |
            dist

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: display branch name
        shell: bash
        run: echo "${{ steps.extract_branch.outputs.branch }}"

      - name: Publish
        uses: qld-gov-au/gha-publish-to-git@master
        with:
          repository: ${{ vars.TARGET_REPO }}
          branch: '${{ steps.extract_branch.outputs.branch }}'
          github_token: '${{ secrets.GH_TOKEN }}'
          github_pat: '${{ secrets.GH_PAT }}'
          git_ref: '${{ github.ref }}'
          source_folder: dist
        if: success()
